name: PR Console log

on:
  pull_request:
    branches:
      - main

jobs:
  print-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        run: echo "Environment Variable: ${{ env.MY_ENV_VAR }}"
        env:
          MY_ENV_VAR: "This is a public environment variable"

      - name: Print secret environment variable
        run: echo "Secret Variable: ${{ secrets.MY_SECRET }}"
